__title__ = 'Triple'
__description__ = 'Triple'
__url__ = 'https://github.com/SantaSpeen/Triple-send'
__version__ = "0.8.2"
__build__ = 644
__author__ = "Maxim Khomutov"
__author_email__ = 'santaspeen@gmail.com'
__license__ = "MIT"
__copyright__ = 'Copyright 2022 Maxim Khomutov'
